 cloud:
    aws:
      credentials:
        accessKey: AKIA3LO7BCKF3XKN2MX5
        secretKey: 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
      region:
        static: us-east-1
 logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error

            